### ISSUE TITLE
XState-Viz: Update Link to Visualizer

### ISSUE THREAD

**Issue by amitnovick** [statecharts/statecharts.github.io#40]
## Description

The link to the XState-Viz live Visualizer app redirects to an older version (that seems to be broken in some cases that were already fixed in the newer version).

## Suggestion

Redirect visits from `https://statecharts.github.io/xstate-viz/` to `https://xstate.js.org/viz/`

**Note**: I couldn't find the link when I searched for it in this repo, but the domain is the same so I thought this issue should be filed here.

**Comment by davidkpiano** [comment]
It now redirects.

**Comment by amitnovick** [comment]
> It now redirects.

Great! I'll close this then.
