### ISSUE TITLE
WYSIWYG editor for state charts?

### ISSUE THREAD

**Issue by zachvalenta** [statecharts/statecharts.github.io#44]
Is there something like https://sequencediagram.org/ for state charts?

If such a thing exists, happy to open PR to add to site; the site has a ['how to use' section](https://statecharts.github.io/how-to-use-statecharts.html) but not a 'how to make' section.

You guys made Hacker News (https://news.ycombinator.com/item?id=21867990) and when I saw the article the first thing I thought was, "Cool, how to make a hello world state chart?".

**Comment by coodoo** [comment]
I built stateskit.com a while back, might fit your needs! 😀

**Comment by zachvalenta** [comment]
Looks pretty cool. Want to (want me to) add a link to it on the site?
